name: Run StreamWide Scraper

on:
  workflow_dispatch:
    inputs:
      movie_url:
        description: 'Movie URL'
        required: true
  repository_dispatch:
    types: [run_scraper]

permissions:
  contents: write # برای ذخیره فایل در گیت‌هاب

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml

      - name: Run Scraper
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CF_WORKER_URL: ${{ secrets.CF_WORKER_URL }}
          MOVIE_URL: ${{ github.event.client_payload.movie_url || github.event.inputs.movie_url }}
        run: python scraper.py

      - name: Commit and push processed URLs
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add processed_urls.txt
          git commit -m "Added processed URL: ${{ github.event.client_payload.movie_url || github.event.inputs.movie_url }}" || echo "No changes to commit"
          git push
